# Generated by Django 4.2.10 on 2024-05-28 09:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_equip', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('representation_unit', models.CharField(max_length=128)),
                ('representation_code', models.CharField(max_length=200)),
                ('representation_period', models.IntegerField(help_text='number of months', validators=[django.core.validators.MinValueValidator(1)])),
                ('expire', models.DateTimeField()),
                ('state_code', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('equipment_model', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=32)),
                ('image', models.FileField(upload_to='docs')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('reason_operator', models.TextField()),
                ('reason_repairman', models.TextField(null=True)),
                ('repair_date', models.DateTimeField(null=True)),
                ('repair_code', models.UUIDField(unique=True)),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.equipment', to_field='state_code')),
            ],
        ),
    ]
