# Generated by Django 4.2.10 on 2024-06-02 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='country',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='expire',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='representation_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='representation_period',
            field=models.IntegerField(blank=True, help_text='number of months', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='representation_unit',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
