# Generated by Django 4.2.10 on 2024-06-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factory', '0002_alter_equipment_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
